[features]
seeds = false
[programs.devnet]
backend = "FqSk7oCrBdrowe6yaLi7fUw1VbHyfxkXUuyDuWtSgEki"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/livesetup/.config/solana/id.json"

[scripts]
test = "node tests/backend.js"
